version: ~> 1.0

dist: focal
os: linux
virt: lxd

language: ruby
cache:
- bundler

env:
- JRUBY_OPTS="--debug"
rvm:
- jruby
- 2.7
- 2.6
- 2.5

before_install:
- yes | gem update --system --force
- bundle config set without 'development debug'

notifications:
  slack:
    rooms:
    - secure: fXYggrDRoLB/4yvyW0kWwyrV5yWa/GC0btPyGu7Hx6ZOaXDC+ejiXSfx7nRyY+uZBs5UF12O4gkUXwBbnWDT5JtQRxzZd5s0cyeGQfAakALexI+FuR2jDcV1prCCaYI4IYoUt61MlfDmuCYVm8hGZ3qsgk/GPHHPnZ8a1FBd2ls=
    - secure: Q040tRLdHrElwYAcDkIBkuDFsF7Fql/QcJT9opMfMOUKkKNNXdCts911vhROu3gbgRrfvngPvza0iDNdRETmJM5lyrFw6IQp9FkrDInHDlymwwFx62bmtk4DE56CkNfgnmpKQH0hSmIipJcHYqgkCzSCv9fxzcX5wMO9yl5/Dao=
